project:
  type: book
  output-dir: docs

number-sections: false  

# Quarto options for books
# https://quarto.org/docs/reference/projects/books.html  

book:
  title: "Quarto Book Template"
  author:
    - name: "Author Name"
      orcid: 0000-0000-0000-0000
      affiliations:
        - name: "TIB – Leibniz Information Centre for Science and Technology"
  date: "today"
  doi: "10.0000/zenodo.0000000"
  chapters:
    - index.qmd
    - ch1.qmd
    - ch2.qmd
    - ch3.qmd
    - ch4.qmd
    - ch5.qmd
  cover-image: images/cover.png
  repo-url: https://github.com/mrchristian/quarto-book-template
  repo-actions: [edit, source, issue]
  downloads: [pdf, docx, epub]

format:
  # options for HTML output
  # https://quarto.org/docs/reference/formats/html.html
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  docx: 
    toc: true
  epub: 
    toc: true      

# Quarto allows commenting using either Hypothesis or Utterances
# https://quarto.org/docs/reference/projects/books.html#comments
comments:
  hypothesis: false

